### ISSUE TITLE
CANNOT OPEN ALL THE PICS 

### ISSUE THREAD

**Issue by xxiong95** [elasticsearch-cn/elasticsearch-definitive-guide#466]

**Comment by medcl** [comment]
what's that mean? details please

**Comment by xxiong95** [comment]
For example.  
When I try to open Figure 1 in elasticsearch-definitive-guide/020_Distributed_Cluster/05_Empty_cluster.asciidoc. It goes to a 404 page

**Comment by medcl** [comment]
i don't see anything wrong with this page:
http://elasticsearch.cn/book/elasticsearch_definitive_guide_2.x/_an-empty-cluster.html#img-cluster

**Comment by xxiong95** [comment]
it sees i cannot view a pic on github like this page https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/blob/cn/020_Distributed_Cluster/05_Empty_cluster.asciidoc

but on your page the pic is visible thanks
