### ISSUE TITLE
翻译纠错

### ISSUE THREAD

**Issue by jiaorenyu** [elasticsearch-cn/elasticsearch-definitive-guide#512]
- 数据建模-通过子文档查询父文档, 最后：

> has_child 查询和过滤在运行机制上类似， 区别是 has_child 过滤不支持 source_mode 参数。has_child 过滤仅用于筛选内容--如内部的一个 filtered 查询--和其他过滤行为类似：包含或者排除，但没有进行评分。
has_child 过滤的结果没有被缓存，但是 has_child 过滤内部的过滤方法适用于通常的缓存规则。

source_mode应该是score_mode

- 在数据建模-通过父文档查询子文档

> 虽然 nested 查询只能返回最顶层的文档 ，但是父文档和子文档本身是彼此独立并且可被单独查询的。我们使用 has_child 语句可以基于子文档来查询父文档，使用 has_parent 语句可以基于子文档来查询父文档。

”使用 has_parent 语句可以基于子文档来查询父文档“这句话应该改为“使用 has_parent 语句可以基于父文档来查询子文档”

**Comment by medcl** [comment]
感谢，可以帮忙提交一个pr么？

**Comment by jiaorenyu** [comment]
已经提交了。发现QQ群好像已经满了，加不进去了。
