### ISSUE TITLE
ES安装plugin插件命令改变

### ISSUE THREAD

**Issue by Hinsteny** [elasticsearch-cn/elasticsearch-definitive-guide#524]
Windows环境下es 5.6.2版本中, 安装插件的命令是 `kibana-plugin.bat`, 请在以下文档中做更新  [install sense](https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/blob/cn/010_Intro/10_Installing_ES.asciidoc)

`bin\kibana-plugin.bat install elastic/sense`

**Comment by medcl** [comment]
权威指南目前是2.x，5.x 的修改后面统一再更新。
