### ISSUE TITLE
新版的文档，比起旧版来，好似没有一个地方可以查看目录啊

### ISSUE THREAD

**Issue by hheedat** [elasticsearch-cn/elasticsearch-definitive-guide#525]
`https://www.elastic.co/guide/cn/elasticsearch/guide/current/index.html`

新版的文档比起以前gitbook的文档，没有地方来查看整个目录，在特定的查找时反而不方便了

**Comment by medcl** [comment]
可以使用搜索的，另外在每页的导航也都是可以看到完整的目录的。

**Comment by hheedat** [comment]
@medcl 是可以的，为啥我上次没找到，汗了
