### ISSUE TITLE
我想自己把该项目转出PDF该怎么做？

### ISSUE THREAD

**Issue by b3601993** [elasticsearch-cn/elasticsearch-definitive-guide#526]
我想转出PDF来看，虽然我知道官网里有，但是最新的毕竟是源码库。本人只用于学习，目前正在学习elasticsearch，自己也翻译版本5的文档，当然没有你们翻译的好

**Comment by medcl** [comment]
`./docs/build_docs.pl --doc   kibana/docs/getting-started/tutorial-dashboard.asciidoc --out kb-book-output/ --chunk=1  --lang=zh --pdf
`
参照本项目 wiki

**Comment by microidea** [comment]
wiki 是更新过了吗？似乎并没有关于导出 PDF 的内容，而且并没有找到 build_docs.pl 这个文件啊

**Comment by biyuhao** [comment]
`build_docs.pl` 脚本位于该项目中 https://github.com/elastic/docs
具体参数可以参阅对应文档
