### ISSUE TITLE
关于精确查找

### ISSUE THREAD

**Issue by Ramlinbird** [elasticsearch-cn/elasticsearch-definitive-guide#567]
https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/blob/cn/080_Structured_Search/20_contains.asciidoc
中提到的“{ "tags" : ["search", "open_source"], "tag_count" : 2 }”好像不能达到所说的精确匹配吧？因为terms查找是一个满足即可，所以上面的查询语句也可以匹配{ "tags" : ["search", "others"], "tag_count" : 2 }这种文档？

**Comment by medcl** [comment]
这里的精确是 term 的值的精确匹配操作，如果你有多个 term，term 之间的关系这个是另外的操作，可以设置 operator 来限制多个条件都必须同时满足。
