### ISSUE TITLE
使用HighLevelClient搜索ES服务器，用Jmeter压测200个线程时响应很慢，不支持高并发么？

### ISSUE THREAD

**Issue by lining0031** [elasticsearch-cn/elasticsearch-definitive-guide#570]
用Jmeter压测时，每个线程第一次请求都会耗时800ms左右，这样200个线程就需要等待160s。第一次请求都慢，第二次请求就会很快响应，大概20ms，为什么会出现这种情况？我已经禁用了ping和嗅探，求指点。

**Comment by biyuhao** [comment]
@lining0031 
由于并未提供具体信息（例如具体请求等），仅从描述上看可能是后面的请求命中了缓存
ES使用相关问题建议移步中文社区提问 https://elasticsearch.cn/
将关闭这个issue
