### ISSUE TITLE
图片为什么都挂了

### ISSUE THREAD

**Issue by Pantheooon** [elasticsearch-cn/elasticsearch-definitive-guide#579]
很多图片都挂了啊看不了

**Comment by medcl** [comment]
是这个地址看的么？
https://www.elastic.co/guide/cn/elasticsearch/guide/current/index.html

**Comment by Pantheooon** [comment]
我直接在GitHub上看的,好的

**Comment by garfieldkai** [comment]
我现在看github上面，图片也都是挂的，不知道为什么，404

**Comment by openSupporter237** [comment]
可以看这个站点 https://es.xiaoleilu.com/
